sudo: required
services: 
  - docker

before_install:
  - docker build -t namkyu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true namkyu/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "hackathon"
  env: "Hackathon-env"
  bucket_name: "elasticbeanstalk-us-east-1-012639386262"
  bucket_path: "Hackathon-env"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"